### ISSUE TITLE
a11y

### ISSUE THREAD

**Issue by barnabywalker** [stevenpbachman/shinygeocat#12]
Need to add accessibility to meet some standards, these might help:

https:/educationshinyappteam.github.io/Style_Guide/accessibility.html

https://github.com/ewenme/shinya11y

**Comment by stevenpbachman** [comment]
I think we are aiming for Web Content Accessibility Guidelines (WCAG) 2.1 at the AA standard

**Comment by gistin** [comment]
Done by Tim
