### ISSUE TITLE
GBIF occurrence request fails sometimes

### ISSUE THREAD

**Issue by barnabywalker** [stevenpbachman/shinygeocat#23]
Getting points from GBIF fails, I think when the GBIF name search returns two names with the same confidence, e.g. `poa annua`.

This passes more than one IPNI ID to WCVP, which doesn't like it.

We could resolve it by:
- using the GBIF results to filter on status
- mapping the WCVP lookup across names and then filtering based on the results
- something else?

**Comment by stevenpbachman** [comment]
good spot. I think it is this bit on `name_search` function
`  # and filter on maximum confidence from GBIF search
  # ensures there is only one result
  gbif_knms = slice_max(gbif_knms, .data$confidence, n=1)`

This only works if there is a distinct number for confidence, and the two values you get with `Poa annua` are both 99.
1 Poa annua   8422205 Poa annua Cham. & Schltdl. SPECIES         99 Poace~ TRUE    416502~
2 Poa annua   2704179 Poa annua L.               SPECIES         99 Poace~ TRUE    320035~

So there is not much else to filter on. We could go with the first value in the table, but in this case it is the wrong one!

Can you pls explain more on "mapping the WCVP lookup across names and then filtering based on the results"

**Comment by stevenpbachman** [comment]
just a note  - `gbif_knms = slice_max(gbif_knms, .data$confidence, n=1, with_ties = FALSE)` would select the first value. This would prevent the error, but would not select the right species.

**Comment by barnabywalker** [comment]
Solved by simplified GBIF import (#42), which just uses the raw name without any matching.
