### ISSUE TITLE
add latitude and longitude graticules

### ISSUE THREAD

**Issue by stevenpbachman** [stevenpbachman/shinygeocat#39]
useful for checking map position https://github.com/Leaflet/Leaflet.Graticule

**Comment by gistin** [comment]
Unfortunately, javascript only, so not sure how to pass this on in R. If we can crack this it would help with other leaflet stuff.

**Comment by gistin** [comment]
Is this needed now you have lat long of the mouse pointer at the top?

**Comment by gistin** [comment]
@stevenpbachman is this needed now we have mouse lat longs at top of map. on small screens, graticules may make the map too cluttered?
