### ISSUE TITLE
Something is wrong with import_csv

### ISSUE THREAD

**Issue by gistin** [stevenpbachman/shinygeocat#57]
Throwing an error, looks like something is missing? line 18 in import-data. I think str_to_lower needs something to work with!

**Comment by gistin** [comment]
![image](https://user-images.githubusercontent.com/1087338/218173190-6b633100-6a79-4660-9428-2a3f08dacaef.png)

**Comment by barnabywalker** [comment]
Should be fixed as of https://github.com/stevenpbachman/shinygeocat/commit/7247a4de0918c357d1f21acff92863c408bb791a, will close when mapping branch is merged.

**Comment by barnabywalker** [comment]
closed by #62
