### ISSUE TITLE
gbif search error on vepris elegantissima

### ISSUE THREAD

**Issue by stevenpbachman** [stevenpbachman/shinygeocat#63]
name matched, but no points to display.
https://www.gbif.org/species/3834586

Assigned data `paste0("gbif", seq(1, nrow(points)))` must be compatible with existing data.
✖ Existing data has 0 rows.
✖ Assigned data has 2 rows.
ℹ Only vectors of size 1 are recycled.

**Comment by gistin** [comment]
Also get same error with species with no result. ie xx. Searching for "Cocos nucifera" gets no results but "Cocos nucifera L." get results. I think the search is a little too specific.

**Comment by barnabywalker** [comment]
At some point this got fixed and the user is prompted to check the GBIF backbone instead.

Justin's issue is more of an enhancement than a bug, so making a new issue.
