### ISSUE TITLE
GBIF data import

### ISSUE THREAD

**Issue by barnabywalker** [stevenpbachman/shinygeocat#8]
Import occurrence data for a species from GBIF, limiting them to:

* points with coordinates
* points with no geospatial issue

Things to think about in the future could be:

* highlighting points by their basis of record
* highlighting points in the same cluster (possible duplicates)
* only getting points by their basis of record

**Comment by stevenpbachman** [comment]
Partially resolved with commits 45af2a85cdb25abbb82609f7dbdea26edb7d4c5a and 19d50e39003ccb401452649ea9ec9a45ca112300
Can you please check @barnabywalker

**Comment by barnabywalker** [comment]
closed a couple of times, latest with #42
